"""
Embedding storage utilities.

This module is responsible for saving and loading
face embeddings generated by FaceEncoder.

Each embedding is stored as a NumPy (.npy) file.

Example:

data/
└── embeddings/
    ├── abbas.npy
    ├── ali.npy
    └── sara.npy
"""

from pathlib import Path
import numpy as np


class EmbeddingStorage:
    """
    Manage stored face embeddings.
    """

    def __init__(self, embeddings_root: str):
        """
        Store the root directory that contains all embeddings.
        """

        self.embeddings_root = Path(embeddings_root)

    def save_embedding(
        self,
        user_name: str,
        embedding: np.ndarray,
    ) -> Path:
        """
        Save one face embedding to disk.

        Parameters
        ----------
        user_name
            Name of the authorized user.

        embedding
            512-dimensional embedding generated by ArcFace.

        Returns
        -------
        Path
            Path of the saved embedding file.
        """

        # Create the embeddings directory if it does not exist.
        self.embeddings_root.mkdir(
            parents=True,
            exist_ok=True,
        )

        embedding_path = (
            self.embeddings_root /
            f"{user_name}.npy"
        )

        np.save(
            embedding_path,
            embedding,
        )

        return embedding_path
    
    def load_embedding(
        self,
        user_name: str,
    ) -> np.ndarray | None:
        """
        Load one face embedding from disk.

        Parameters
        ----------
        user_name
            Name of the authorized user.

        Returns
        -------
        np.ndarray | None
            The stored embedding if it exists.
            Otherwise, return None.
        """

        embedding_path = (
            self.embeddings_root /
            f"{user_name}.npy"
        )

        if not embedding_path.exists():
            return None

        return np.load(embedding_path)
    
    def delete_embedding(
        self,
        user_name: str,
    ) -> bool:
        """
        Delete a stored embedding.

        Parameters
        ----------
        user_name
            Name of the authorized user.

        Returns
        -------
        bool
            True if the embedding was deleted.
            False if the embedding did not exist.
        """

        embedding_path = (
            self.embeddings_root /
            f"{user_name}.npy"
        )

        if not embedding_path.exists():
            return False

        embedding_path.unlink()

        return True
    
    def embedding_exists(
        self,
        user_name: str,
    ) -> bool:
        """
        Check whether an embedding exists.
        """

        embedding_path = (
            self.embeddings_root /
            f"{user_name}.npy"
        )

        return embedding_path.exists()
    
    def list_embeddings(self) -> list[Path]:
        """
        Return all stored embedding files.
        """

        if not self.embeddings_root.exists():
            return []

        return sorted(
            self.embeddings_root.glob("*.npy")
        )