"""
Security event logging utilities.

This module stores access-control events generated by
the face recognition system.

The first implementation writes events to a CSV file.
Later, this can be extended to SQLite or another database.
"""

import csv
import cv2
from datetime import datetime
from pathlib import Path


class EventLogger:
    """
    Log access-control events to a CSV file.
    """

    def __init__(self, log_path: str = "data/logs/access_events.csv"):
        """
        Initialize the event logger.

        The log directory is created automatically so the
        application can run even if the logs folder does not exist yet.
        """

        self.log_path = Path(log_path)

        self.log_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        self.fieldnames = [
            "timestamp",
            "user_name",
            "access_granted",
            "similarity",
            "camera",
            "fps",
            "recognition_time_ms",
            "temperature",
            "image_path",
            "reason",
        ]

        if not self.log_path.exists():
            self._write_header()

    def _write_header(self):
        """
        Write the CSV header once when the log file is created.
        """

        with self.log_path.open(
            mode="w",
            newline="",
            encoding="utf-8",
        ) as file:
            writer = csv.DictWriter(
                file,
                fieldnames=self.fieldnames,
            )

            writer.writeheader()

    def log_event(
        self,
        user_name: str,
        access_granted: bool,
        similarity: float,
        camera: str,
        fps: float,
        recognition_time_ms: float,
        temperature: str = "--",
        image_path: str = "",
        reason: str = "",
    ):
        """
        Append one access-control event to the CSV log.
        """

        event = {
            "timestamp": datetime.now().isoformat(timespec="seconds"),
            "user_name": user_name,
            "access_granted": access_granted,
            "similarity": round(similarity, 4),
            "camera": camera,
            "fps": round(fps, 2),
            "recognition_time_ms": round(recognition_time_ms, 2),
            "temperature": temperature,
            "image_path": image_path,
            "reason": reason,
        }

        with self.log_path.open(
            mode="a",
            newline="",
            encoding="utf-8",
        ) as file:
            writer = csv.DictWriter(
                file,
                fieldnames=self.fieldnames,
            )

            writer.writerow(event)

    def save_event_image(
        self,
        image,
        event_name: str,
        images_root: str = "data/events/images",
    ) -> str:
        """
        Save the frame associated with an access-control event.
        """

        images_dir = Path(images_root)
        images_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        image_path = images_dir / f"{timestamp}_{event_name}.jpg"

        cv2.imwrite(
            str(image_path),
            image,
        )

        return str(image_path)